version: '3.8'

services:
  servidor:
    build: .
    command: npm run cenario3:server
    ports:
      - "3000:3000"
    networks:
      - rede-ipc

  cliente:
    build: .
    command: npm run cenario3:client
    depends_on:
      - servidor
    environment:
      - SERVER_HOST=servidor
    networks:
      - rede-ipc

networks:
  rede-ipc:
    driver: bridge
